import {
  getAnimationStyle,
  getBackgroundStyle,
  getBorderRadiusStyle,
  getBorderStyle,
  getBoxShadowStyle,
  getColorStyle,
  getColumnBreakPointStyle,
  getColumnItemsStyle,
  getDisplayStyle,
  getFlexStyle,
  getFluidStyle,
  getFontStyle,
  getGapStyle,
  getHeightStyle,
  getHoverStyle,
  getMarginStyle,
  getOpacityStyle,
  getPaddingStyle,
  getPositionStyle,
  getRoundedStyle,
  getSizeStyle,
  getTextStyle,
  getTransformStyle,
  getTransitionStyle,
  getTranslateStyle,
  getWidthStyle,
} from "./props/getStyle.barrel.index";

export const getStyle = {
  animation: getAnimationStyle,
  background: getBackgroundStyle,
  border: getBorderStyle,
  borderRadius: getBorderRadiusStyle,
  boxShadow: getBoxShadowStyle,
  color: getColorStyle,
  columnBreakPoint: getColumnBreakPointStyle,
  columnItems: getColumnItemsStyle,
  display: getDisplayStyle,
  flex: getFlexStyle,
  fluid: getFluidStyle,
  font: getFontStyle,
  gap: getGapStyle,
  height: getHeightStyle,
  hover: getHoverStyle,
  margin: getMarginStyle,
  opacity: getOpacityStyle,
  padding: getPaddingStyle,
  position: getPositionStyle,
  size: getSizeStyle,
  rounded: getRoundedStyle,
  text: getTextStyle,
  transition: getTransitionStyle,
  translate: getTranslateStyle,
  transform: getTransformStyle,
  width: getWidthStyle,
};
