import {
  getBackgroundStyle,
  getBorderRadiusStyle,
  getBorderStyle,
  getColorStyle,
  getColumnBreakPointStyle,
  getColumnItemsStyle,
  getDisplayStyle,
  getFlexStyle,
  getFontStyle,
  getHeightStyle,
  getMarginStyle,
  getPaddingStyle,
  getPositionStyle,
  getTextStyle,
  getWidthStyle,
} from "./props";

export const getStyle = {
  margin: getMarginStyle,
  padding: getPaddingStyle,
  text: getTextStyle,
  width: getWidthStyle,
  color: getColorStyle,
  background: getBackgroundStyle,
  border: getBorderStyle,
  borderRadius: getBorderRadiusStyle,
  columnBreakPoint: getColumnBreakPointStyle,
  display: getDisplayStyle,
  flex: getFlexStyle,
  columnItems: getColumnItemsStyle,
  font: getFontStyle,
  height: getHeightStyle,
  position: getPositionStyle,
};
